feat(tests): add JSON Schema test coverage
OAI/Arazzo-Specification pull request #286
Opened 2024-11-21 23:33 UTC by jeremyfiel

This PR adds schema test coverage for the JSON Schema, 

this is based on the work in the OAS and Overlay projects by @MikeRalphson and @ralfhandl 

The schema tests do not cover JSON Schema 2020-12 keywords as defined by the `inputs` keyword. All Arazzo specific keywords are covered by the tests.

I've also included markdownlint-cli to clean up the spec file.

2024-11-22 16:31 UTC, jeremyfiel commented
rebased on v1.0.0-dev to resolve conflicts.

2024-11-25 09:10 UTC, ralfhandl reviewed
@jeremyfiel Why is the specification markdown source changed by this PR?

2024-11-25 12:43 UTC, jeremyfiel commented
Markdown lint was added and the rebase onto v1.0.0-dev included some recent updates by Frank   

I didn't change any wording on it

2024-11-25 15:53 UTC, jeremyfiel commented
* stripped out the markdown lint updates
* removed the json version of the schema

2024-11-26 02:03 UTC, jeremyfiel reviewed
mistakenly removed the original `validate-markdown.yaml` with mdv checks.

2024-11-26 09:12 UTC, ralfhandl commented on scripts/format-markdown.sh
This file should be removed from this PR and only part of #291

2024-11-26 14:49 UTC, jeremyfiel commented on scripts/format-markdown.sh
done

2024-11-26 14:51 UTC, jeremyfiel commented
opps. somehow the validate-markdown.yaml was deleted again. added it back.

2024-12-16 12:44 UTC, frankkilcommins requested changes
Thanks @jeremyfiel - i'm requested changed on the examples to ensure they are valid (which is being fixed for the examples directly in #260 )

Can you also take a look at the merge conflicts?

2024-12-16 12:44 UTC, frankkilcommins commented on schemas/v1.0/readme.md
> +Here you can find the JSON Schema for validating Arazzos of versions 1.0.x.
```suggestion
Here you can find the JSON Schema for validating Arazzo Documents conforming to versions 1.0.x.
```

2024-12-16 12:44 UTC, frankkilcommins commented on tests/v1.0/pass/bnpl-example.yaml
> +          - condition: $response.body.existingCustomerNotEligible == false
```suggestion
          - condition: $response.body#/existingCustomerNotEligible == false
```

2024-12-16 12:44 UTC, frankkilcommins commented on tests/v1.0/pass/bnpl-example.yaml
> +      totalLoanAmount: $response.body.totalAmount
```suggestion
      eligibilityCheckRequired: $response.body#/eligibilityCheckRequired
      eligibleProducts: $response.body#/products
      totalLoanAmount: $response.body#/totalAmount
```

2024-12-16 12:44 UTC, frankkilcommins commented on tests/v1.0/pass/bnpl-example.yaml
> +      customer: $response.body.links.self
```suggestion
      customer: $response.body#/links/self
```

2024-12-16 12:44 UTC, frankkilcommins commented on tests/v1.0/pass/bnpl-example.yaml
> +          - condition: $response.body.redirectAuthToken != null
```suggestion
          - condition: $response.body#/redirectAuthToken != null
```

2024-12-16 12:44 UTC, frankkilcommins commented on tests/v1.0/pass/bnpl-example.yaml
> +          - condition: $response.body.redirectAuthToken == null
```suggestion
          - condition: $response.body#/redirectAuthToken == null
```

2024-12-16 12:44 UTC, frankkilcommins commented on tests/v1.0/pass/bnpl-example.yaml
> +      loanTransactionResourceUrl: $response.body.links.self
```suggestion
      redirectAuthToken: $response.body#/redirectAuthToken
      loanTransactionResourceUrl: $response.body#/links/self
```

2024-12-16 12:44 UTC, frankkilcommins commented on tests/v1.0/pass/bnpl-example.yaml
> +    finalizedPaymentPlan: $steps.retrieveFinalizedPaymentPlan.finalizedPaymentPlan
```suggestion
    finalizedPaymentPlan: $steps.retrieveFinalizedPaymentPlan.outputs.finalizedPaymentPlan
```

2024-12-16 12:44 UTC, frankkilcommins commented on tests/v1.0/pass/oauth-example.yaml
> +          expires_in: $response.body.expires_in
```suggestion
          access_token: $response.body#/access_token
          refresh_token: $response.body#/refresh_token
          expires_in: $response.body#/expires_in
```

2024-12-16 12:44 UTC, frankkilcommins commented on tests/v1.0/pass/oauth-example.yaml
> +          access_token: $response.body.access_token
```suggestion
          access_token: $response.body#/access_token
```

2024-12-16 12:44 UTC, frankkilcommins commented on tests/v1.0/pass/oauth-example.yaml
> +          code: $response.body.code  # Not really, this is a query parameter
```suggestion
          code: $response.body#/code  # Not really, this is a query parameter
```

2024-12-16 12:44 UTC, frankkilcommins commented on tests/v1.0/pass/oauth-example.yaml
> +          expires_in: $response.body.expires_in
```suggestion
          access_token: $response.body#/access_token
          refresh_token: $response.body#/refresh_token
          expires_in: $response.body#/expires_in
```

2024-12-16 12:44 UTC, frankkilcommins commented on tests/v1.0/pass/pet-coupons-example.yaml
> +          my_pet_id: $outputs[0].id
```suggestion
          my_pet_id: $response.body#/0/id
```

2024-12-16 12:44 UTC, frankkilcommins commented on tests/v1.0/pass/pet-coupons-example.yaml
> +          my_coupon_code: $response.body.couponCode
```suggestion
          my_coupon_code: $response.body#/couponCode
```

2024-12-16 12:44 UTC, frankkilcommins commented on tests/v1.0/pass/pet-coupons-example.yaml
> +          my_order_id: $workflow_order_id
```suggestion
          my_order_id: $outputs.workflow_order_id
```

2024-12-16 12:44 UTC, frankkilcommins commented on tests/v1.0/pass/pet-coupons-example.yaml
> +          my_pet_id: $outputs[0].id
```suggestion
          my_pet_id: $response.body#/0/id
```

2024-12-16 12:44 UTC, frankkilcommins commented on tests/v1.0/pass/pet-coupons-example.yaml
> +          my_order_id: $workflow_order_id
```suggestion
          my_order_id: $outputs.workflow_order_id
```

2024-12-16 12:44 UTC, frankkilcommins commented on tests/v1.0/pass/pet-coupons-example.yaml
> +          step_order_id: $response.body.id
```suggestion
          step_order_id: $response.body#/id
```

2024-12-16 22:41 UTC, jeremyfiel commented
tbh, i'm not sure why this is a conflict. the file currently exists on `v1.0.0-dev` and is requested to be deleted in this PR. so it shouldn't conflict with anything.

2024-12-16 22:57 UTC, jeremyfiel commented
interesting. adding the file back removes the conflict. I can create a separate pr to remove the file after this is merged.. lmk if that works

2024-12-16 23:07 UTC, jeremyfiel commented
taking inspiration from @ralfhandl  to update the schema test coverage threshold to 100% like [this](https://github.com/OAI/Overlay-Specification/pull/109/files) will not work for this repo because we are not testing the JSON Schema 2020-12 keywords used in `inputs`.  I'm not sure if we want to peg it to ~63% coverage to indicate the threshold is met or not.  To be discussed...

2024-12-17 10:02 UTC, frankkilcommins approved these changes

2024-12-17 10:04 UTC, merged